/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewRestaurantIdRouteImport } from './routes/review.$restaurantId'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRestaurantIdRoute = ReviewRestaurantIdRouteImport.update({
  id: '/review/$restaurantId',
  path: '/review/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/review/$restaurantId': typeof ReviewRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/review/$restaurantId': typeof ReviewRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/review/$restaurantId': typeof ReviewRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/copilot'
    | '/dashboard'
    | '/reviews'
    | '/api/copilot'
    | '/review/$restaurantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/copilot'
    | '/dashboard'
    | '/reviews'
    | '/api/copilot'
    | '/review/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/reviews'
    | '/api/copilot'
    | '/review/$restaurantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ReviewRestaurantIdRoute: typeof ReviewRestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$restaurantId': {
      id: '/review/$restaurantId'
      path: '/review/$restaurantId'
      fullPath: '/review/$restaurantId'
      preLoaderRoute: typeof ReviewRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ReviewRestaurantIdRoute: ReviewRestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
